In [58]:
import nltk
import pandas as pd
from pprint import pprint
from collections import Counter
import random
import difflib
from wordfreq import zipf_frequency
from nltk.corpus import wordnet as wn

In [59]:
#prendi il primo synset nominale di WordNet associato alla parola "vehicle".
vehicle = wn.synset("vehicle.n.01")

print(vehicle)
print(vehicle.definition())
print()

Synset('vehicle.n.01')
a conveyance that transports people or objects

In [60]:
#Analisi esplorativa di iponomi di Vehicle nodo 1
for synset in vehicle.hyponyms():
    print(synset.name(), "-", synset.definition())

rocket.n.01 - any vehicle self-propelled by a rocket engine
craft.n.02 - a vehicle designed for navigation in or on water or air or through outer space
bumper_car.n.01 - a small low-powered electrically powered vehicle driven on a special platform where there are many others to be dodged
steamroller.n.02 - vehicle equipped with heavy wide smooth rollers for compacting roads and pavements
skibob.n.01 - a vehicle resembling a bicycle but having skis instead of wheels; the rider wears short skis for balancing
sled.n.01 - a vehicle mounted on runners and pulled by horses or dogs; for transportation over snow
military_vehicle.n.01 - vehicle used by the armed forces
wheeled_vehicle.n.01 - a vehicle that moves on wheels and usually has a container for transporting things or people

In [61]:
#Analisi esplorativa di iponomi di Vehicle nodo 2
for synset in vehicle.hyponyms():
    print("\n", synset.name(), "-", synset.definition())
    
    for child in synset.hyponyms():
        print("   ->", child.name(), "-", child.definition())

 rocket.n.01 - any vehicle self-propelled by a rocket engine
   -> test_rocket.n.01 - a rocket fired for test purposes
   -> multistage_rocket.n.01 - a rocket having two or more rocket engines (each with its own fuel) that are fired in succession and jettisoned when the fuel is exhausted
   -> missile.n.01 - a rocket carrying a warhead of conventional or nuclear explosives; may be ballistic or directed by remote control

 craft.n.02 - a vehicle designed for navigation in or on water or air or through outer space
   -> aircraft.n.01 - a vehicle that can fly
   -> landing_craft.n.01 - naval craft designed for putting ashore troops and equipment
   -> vessel.n.02 - a craft designed for water transportation
   -> hovercraft.n.01 - a craft capable of moving over water or land on a cushion of air created by jet engines
   -> spacecraft.n.01 - a craft capable of traveling in outer space; technically, a satellite around the sun

 bumper_car.n.01 - a small low-powered electrically powered vehicle driven on a special platform where there are many others to be dodged

 steamroller.n.02 - vehicle equipped with heavy wide smooth rollers for compacting roads and pavements

 skibob.n.01 - a vehicle resembling a bicycle but having skis instead of wheels; the rider wears short skis for balancing

 sled.n.01 - a vehicle mounted on runners and pulled by horses or dogs; for transportation over snow
   -> bobsled.n.01 - formerly two short sleds coupled together
   -> dogsled.n.01 - a sled pulled by dogs
   -> pung.n.01 - a one-horse sleigh consisting of a box on runners
   -> luge.n.01 - a racing sled for one or two people
   -> bobsled.n.02 - a long racing sled (for 2 or more people) with a steering mechanism
   -> toboggan.n.01 - a long narrow sled without runners; boards curve upward in front

 military_vehicle.n.01 - vehicle used by the armed forces
   -> weapons_carrier.n.01 - military vehicle that is a light truck designed to carry mortars or machine guns and their crews
   -> tank.n.01 - an enclosed armored military vehicle; has a cannon and moves on caterpillar treads
   -> warplane.n.01 - an aircraft designed and used for combat
   -> caisson.n.02 - a two-wheeled military vehicle carrying artillery ammunition
   -> reconnaissance_vehicle.n.01 - fast armored military vehicle with four-wheel drive and open top
   -> humvee.n.01 - a high mobility, multipurpose, military vehicle with four-wheel drive
   -> warship.n.01 - a government ship that is available for waging war
   -> picket.n.04 - a vehicle performing sentinel duty
   -> technical.n.01 - a pickup truck with a gun mounted on it
   -> troop_carrier.n.01 - any land or sea or air vehicle designed to carry troops
   -> half_track.n.01 - a motor vehicle propelled by half tracks; frequently used by the military
   -> personnel_carrier.n.01 - a military vehicle (usually armored) for transporting military personnel and their equipment

 wheeled_vehicle.n.01 - a vehicle that moves on wheels and usually has a container for transporting things or people
   -> unicycle.n.01 - a vehicle with a single wheel that is driven by pedals
   -> skateboard.n.01 - a board with wheels that is ridden in a standing or crouching position and propelled by foot
   -> boneshaker.n.01 - any wheeled vehicle that is dilapidated and uncomfortable
   -> baby_buggy.n.01 - a small vehicle with four wheels in which a baby or child is pushed around
   -> motor_scooter.n.01 - a wheeled vehicle with small wheels and a low-powered gasoline engine geared to the rear wheel
   -> welcome_wagon.n.01 - a wheeled vehicle carrying information and gifts from local merchants for new residents in an area
   -> tricycle.n.01 - a vehicle with three wheels that is moved by foot pedals
   -> trailer.n.04 - a wheeled vehicle that can be pulled by a car or truck and is equipped for occupancy
   -> horse-drawn_vehicle.n.01 - a wheeled vehicle drawn by one or more horses
   -> self-propelled_vehicle.n.01 - a wheeled vehicle that carries in itself a means of propulsion
   -> handcart.n.01 - wheeled vehicle that can be pushed by a person; may have one or two or four wheels
   -> car.n.02 - a wheeled vehicle adapted to the rails of railroad
   -> wagon.n.04 - a child's four-wheeled toy cart sometimes used for coasting
   -> scooter.n.02 - child's two-wheeled vehicle operated by foot
   -> bicycle.n.01 - a wheeled vehicle that has two wheels and is moved by foot pedals
   -> wagon.n.01 - any of various kinds of wheeled vehicles drawn by an animal or a tractor
   -> rolling_stock.n.01 - collection of wheeled vehicles owned by a railroad or motor carrier

In [62]:
#Analisi esplorativa di iponomi di Vehicle nodo 3
for synset in vehicle.hyponyms():
    
    print("\n", synset.name(), "-", synset.definition())

    for child in synset.hyponyms():
        
        print("   ->", child.name(), "-", child.definition())

        for grandchild in child.hyponyms():
            print("      ->", grandchild.name(), "-", grandchild.definition())

 rocket.n.01 - any vehicle self-propelled by a rocket engine
   -> test_rocket.n.01 - a rocket fired for test purposes
      -> sounding_rocket.n.01 - a research rocket used to obtain information about the atmosphere at various altitudes
   -> multistage_rocket.n.01 - a rocket having two or more rocket engines (each with its own fuel) that are fired in succession and jettisoned when the fuel is exhausted
   -> missile.n.01 - a rocket carrying a warhead of conventional or nuclear explosives; may be ballistic or directed by remote control
      -> guided_missile.n.01 - a rocket-propelled missile whose path can be controlled during flight either by radio signals or by internal homing devices
      -> air-to-ground_missile.n.01 - a missile designed to be launched from an airplane at a target on the ground
      -> heat-seeking_missile.n.01 - a missile with a guidance system that directs it toward targets emitting infrared radiation (as the emissions of a jet engine)
      -> ballistic_missile.n.01 - a missile that is guided in the first part of its flight but falls freely as it approaches target
      -> air-to-air_missile.n.01 - a missile designed to be launched from one airplane at another
      -> sidewinder.n.02 - air-to-air missile with infrared homing device

 craft.n.02 - a vehicle designed for navigation in or on water or air or through outer space
   -> aircraft.n.01 - a vehicle that can fly
      -> stealth_aircraft.n.01 - an aircraft designed in accordance with technology that makes detection by radar difficult
      -> heavier-than-air_craft.n.01 - a non-buoyant aircraft that requires a source of power to hold it aloft and to propel it
      -> cruise_missile.n.01 - an unmanned aircraft that is a self-contained bomb
      -> bogy.n.01 - an unidentified (and possibly enemy) aircraft
      -> lighter-than-air_craft.n.01 - aircraft supported by its own buoyancy
   -> landing_craft.n.01 - naval craft designed for putting ashore troops and equipment
   -> vessel.n.02 - a craft designed for water transportation
      -> galley.n.02 - (classical antiquity) a crescent-shaped seagoing vessel propelled by oars
      -> sailing_vessel.n.01 - a vessel that is powered by the wind; often having several masts
      -> shrimper.n.01 - a vessel engaged in shrimping
      -> fishing_boat.n.01 - a vessel for fishing; often has a well to keep the catch alive
      -> bareboat.n.01 - a vessel (such as a yacht) that can be chartered without a captain or crew or provisions
      -> iceboat.n.02 - a sailing vessel with runners and a cross-shaped frame; suitable for traveling over ice
      -> weather_ship.n.01 - an oceangoing vessel equipped to make meteorological observations
      -> galley.n.01 - a large medieval vessel with a single deck propelled by sails and oars with guns at stern and prow; a complement of 1,000 men; used mainly in the Mediterranean for war and trading
      -> patrol_boat.n.01 - a vessel assigned to patrol an area
      -> ship.n.01 - a vessel that carries passengers or freight
      -> yacht.n.01 - an expensive vessel propelled by sail or power and used for cruising or racing
      -> boat.n.01 - a small vessel for travel on water
   -> hovercraft.n.01 - a craft capable of moving over water or land on a cushion of air created by jet engines
   -> spacecraft.n.01 - a craft capable of traveling in outer space; technically, a satellite around the sun
      -> space_capsule.n.01 - a spacecraft designed to transport people and support human life in outer space
      -> space_shuttle.n.01 - a reusable spacecraft with wings for a controlled descent through the Earth's atmosphere
      -> lunar_excursion_module.n.01 - a spacecraft that carries astronauts from the command module to the surface of the moon and back
      -> starship.n.01 - a spacecraft designed to carry a crew into interstellar space (especially in science fiction)
      -> lander.n.02 - a space vehicle that is designed to land on the moon or another planet

 bumper_car.n.01 - a small low-powered electrically powered vehicle driven on a special platform where there are many others to be dodged

 steamroller.n.02 - vehicle equipped with heavy wide smooth rollers for compacting roads and pavements

 skibob.n.01 - a vehicle resembling a bicycle but having skis instead of wheels; the rider wears short skis for balancing

 sled.n.01 - a vehicle mounted on runners and pulled by horses or dogs; for transportation over snow
   -> bobsled.n.01 - formerly two short sleds coupled together
   -> dogsled.n.01 - a sled pulled by dogs
   -> pung.n.01 - a one-horse sleigh consisting of a box on runners
   -> luge.n.01 - a racing sled for one or two people
   -> bobsled.n.02 - a long racing sled (for 2 or more people) with a steering mechanism
   -> toboggan.n.01 - a long narrow sled without runners; boards curve upward in front

 military_vehicle.n.01 - vehicle used by the armed forces
   -> weapons_carrier.n.01 - military vehicle that is a light truck designed to carry mortars or machine guns and their crews
   -> tank.n.01 - an enclosed armored military vehicle; has a cannon and moves on caterpillar treads
      -> panzer.n.01 - an armored vehicle or tank
   -> warplane.n.01 - an aircraft designed and used for combat
      -> fighter.n.02 - a high-speed military or naval airplane designed to destroy enemy aircraft in the air
      -> reconnaissance_plane.n.01 - a military airplane used to gain information about an enemy
      -> bomber.n.01 - a military aircraft that drops bombs during flight
   -> caisson.n.02 - a two-wheeled military vehicle carrying artillery ammunition
   -> reconnaissance_vehicle.n.01 - fast armored military vehicle with four-wheel drive and open top
   -> humvee.n.01 - a high mobility, multipurpose, military vehicle with four-wheel drive
   -> warship.n.01 - a government ship that is available for waging war
      -> frigate.n.02 - a United States warship larger than a destroyer and smaller than a cruiser
      -> cruiser.n.02 - a large fast warship; smaller than a battleship and larger than a destroyer
      -> destroyer_escort.n.01 - warship smaller than a destroyer; designed to escort fleets or convoys
      -> corvette.n.01 - a highly maneuverable escort warship; smaller than a destroyer
      -> aircraft_carrier.n.01 - a large warship that carries planes and has a long flat deck for takeoffs and landings
      -> destroyer.n.01 - a small fast lightly armored but heavily armed warship
      -> ironclad.n.01 - a wooden warship of the 19th century that is plated with iron or steel armor
      -> man-of-war.n.01 - a warship intended for combat
      -> frigate.n.01 - a medium size square-rigged warship of the 18th and 19th centuries
      -> privateer.n.02 - a privately owned warship commissioned to prey on the commercial shipping or warships of an enemy nation
      -> guard_ship.n.01 - a warship (at anchor or under way) required to maintain a higher degree of readiness than others in its squadron
      -> sloop_of_war.n.01 - a sailing or steam warship having cannons on only one deck
      -> three-decker.n.03 - a warship carrying guns on three decks
      -> capital_ship.n.01 - a warship of the first rank in size and armament
      -> battleship.n.01 - large and heavily armoured warship
      -> submersible.n.02 - a warship designed to operate under water
      -> surface_ship.n.01 - a warship that operates on the surface of the water
      -> torpedo_boat.n.01 - small high-speed warship designed for torpedo attacks in coastal waters
   -> picket.n.04 - a vehicle performing sentinel duty
      -> picket_ship.n.01 - a ship serving as a picket
      -> picket_boat.n.01 - a boat serving as a picket
   -> technical.n.01 - a pickup truck with a gun mounted on it
   -> troop_carrier.n.01 - any land or sea or air vehicle designed to carry troops
      -> troopship.n.01 - ship for transporting troops
   -> half_track.n.01 - a motor vehicle propelled by half tracks; frequently used by the military
   -> personnel_carrier.n.01 - a military vehicle (usually armored) for transporting military personnel and their equipment

 wheeled_vehicle.n.01 - a vehicle that moves on wheels and usually has a container for transporting things or people
   -> unicycle.n.01 - a vehicle with a single wheel that is driven by pedals
   -> skateboard.n.01 - a board with wheels that is ridden in a standing or crouching position and propelled by foot
   -> boneshaker.n.01 - any wheeled vehicle that is dilapidated and uncomfortable
   -> baby_buggy.n.01 - a small vehicle with four wheels in which a baby or child is pushed around
      -> bassinet.n.02 - a perambulator that resembles a bassinet
   -> motor_scooter.n.01 - a wheeled vehicle with small wheels and a low-powered gasoline engine geared to the rear wheel
   -> welcome_wagon.n.01 - a wheeled vehicle carrying information and gifts from local merchants for new residents in an area
   -> tricycle.n.01 - a vehicle with three wheels that is moved by foot pedals
      -> pedicab.n.01 - a tricycle (usually propelled by pedalling); used in the Orient for transporting passengers for hire
   -> trailer.n.04 - a wheeled vehicle that can be pulled by a car or truck and is equipped for occupancy
      -> mobile_home.n.01 - a large house trailer that can be connected to utilities and can be parked in one place and used as permanent housing
      -> camper_trailer.n.01 - a trailer equipped for occupancy (especially for holiday trips)
   -> horse-drawn_vehicle.n.01 - a wheeled vehicle drawn by one or more horses
      -> sulky.n.01 - a light two-wheeled vehicle for one person; drawn by one horse
      -> carriage.n.02 - a vehicle with wheels drawn by one or more horses
      -> limber.n.01 - a two-wheeled horse-drawn vehicle used to pull a field gun or caisson
      -> chariot.n.02 - a two-wheeled horse-drawn battle vehicle; used in war and races in ancient Egypt and Greece and Rome
   -> self-propelled_vehicle.n.01 - a wheeled vehicle that carries in itself a means of propulsion
      -> weapons_carrier.n.01 - military vehicle that is a light truck designed to carry mortars or machine guns and their crews
      -> armored_vehicle.n.01 - a vehicle that is protected by armor plate
      -> carrier.n.02 - a self-propelled wheeled vehicle designed specifically to carry something
      -> tracked_vehicle.n.01 - a self-propelled vehicle that moves on tracks
      -> reconnaissance_vehicle.n.01 - fast armored military vehicle with four-wheel drive and open top
      -> motor_vehicle.n.01 - a self-propelled wheeled vehicle that does not run on rails
      -> recreational_vehicle.n.01 - a motorized wheeled vehicle used for camping or other recreational activities
      -> forklift.n.01 - a small industrial vehicle with a power operated forked platform in front that can be inserted under loads to lift and move them
      -> personnel_carrier.n.01 - a military vehicle (usually armored) for transporting military personnel and their equipment
      -> tractor.n.01 - a wheeled vehicle with large wheels; used in farming and other applications
      -> streetcar.n.01 - a wheeled vehicle that runs on rails and is propelled by electricity
      -> locomotive.n.01 - a wheeled vehicle consisting of a self-propelled engine that is used to draw trains along railway tracks
   -> handcart.n.01 - wheeled vehicle that can be pushed by a person; may have one or two or four wheels
      -> applecart.n.02 - a handcart from which apples and other fruit are sold in the street
      -> laundry_cart.n.01 - handcart for moving a load of laundry
      -> serving_cart.n.01 - a handcart for serving food
      -> barrow.n.03 - a cart for carrying small loads; has handles and one or more wheels
      -> shopping_cart.n.01 - a handcart that holds groceries or other goods while shopping
      -> hand_truck.n.01 - a handcart that has a frame with two low wheels and a ledge at the bottom and handles at the top; used to move crates or other heavy objects
   -> car.n.02 - a wheeled vehicle adapted to the rails of railroad
      -> baggage_car.n.01 - a railway car where passengers' bags are carried
      -> slip_coach.n.01 - a railway car at the end of the train; it can be detached without stopping the train
      -> van.n.03 - (Great Britain) a closed railroad car that carries baggage or freight
      -> freight_car.n.01 - a railway car that carries freight
      -> handcar.n.01 - a small railroad car propelled by hand or by a small motor
      -> tender.n.04 - car attached to a locomotive to carry fuel and water
      -> mail_car.n.01 - a railway car in which mail is transported and sorted
      -> cabin_car.n.01 - a car on a freight train for use of the train crew; usually the last car on the train
      -> guard's_van.n.01 - the car on a train that is occupied by the guard
      -> club_car.n.01 - railroad car having a bar and tables and lounge chairs
      -> passenger_car.n.01 - a railcar where passengers ride
   -> wagon.n.04 - a child's four-wheeled toy cart sometimes used for coasting
   -> scooter.n.02 - child's two-wheeled vehicle operated by foot
   -> bicycle.n.01 - a wheeled vehicle that has two wheels and is moved by foot pedals
      -> safety_bicycle.n.01 - bicycle that has two wheels of equal size; pedals are connected to the rear wheel by a multiplying gear
      -> mountain_bike.n.01 - a bicycle with a sturdy frame and fat tires; originally designed for riding in mountainous country
      -> velocipede.n.01 - any of several early bicycles with pedals on the front wheel
      -> ordinary.n.04 - an early bicycle with a very large front wheel and small back wheel
      -> push-bike.n.01 - a bicycle that must be pedaled
      -> bicycle-built-for-two.n.01 - a bicycle with two sets of pedals and two seats
   -> wagon.n.01 - any of various kinds of wheeled vehicles drawn by an animal or a tractor
      -> milk_wagon.n.01 - wagon for delivering milk
      -> chuck_wagon.n.01 - a wagon equipped with a cookstove and provisions (for cowboys)
      -> cart.n.01 - a heavy open wagon usually having two wheels and drawn by an animal
      -> covered_wagon.n.01 - a large wagon with broad wheels and an arched canvas top; used by the United States pioneers to cross the prairies in the 19th century
      -> tramcar.n.01 - a four-wheeled wagon that runs on tracks in a mine
      -> water_wagon.n.01 - a wagon that carries water (as for troops or work gangs or to sprinkle down dusty dirt roads in the summertime)
      -> lorry.n.01 - a large low horse-drawn wagon without sides
      -> wain.n.03 - large open farm wagon
      -> bandwagon.n.02 - a large ornate wagon for carrying a musical band
      -> ice_wagon.n.01 - (formerly) a horse-drawn wagon that delivered ice door to door
   -> rolling_stock.n.01 - collection of wheeled vehicles owned by a railroad or motor carrier

In [63]:
#funzione per creare lista di iponomi fino a profondità 3 da vehicle
tree = vehicle.tree(lambda s: s.hyponyms(), depth=3)

print(tree)

[Synset('vehicle.n.01'), [Synset('rocket.n.01'), [Synset('test_rocket.n.01'), [Synset('sounding_rocket.n.01')]], [Synset('multistage_rocket.n.01')], [Synset('missile.n.01'), [Synset('guided_missile.n.01')], [Synset('air-to-ground_missile.n.01')], [Synset('heat-seeking_missile.n.01')], [Synset('ballistic_missile.n.01')], [Synset('air-to-air_missile.n.01')], [Synset('sidewinder.n.02')]]], [Synset('craft.n.02'), [Synset('aircraft.n.01'), [Synset('stealth_aircraft.n.01')], [Synset('heavier-than-air_craft.n.01')], [Synset('cruise_missile.n.01')], [Synset('bogy.n.01')], [Synset('lighter-than-air_craft.n.01')]], [Synset('landing_craft.n.01')], [Synset('vessel.n.02'), [Synset('galley.n.02')], [Synset('sailing_vessel.n.01')], [Synset('shrimper.n.01')], [Synset('fishing_boat.n.01')], [Synset('bareboat.n.01')], [Synset('iceboat.n.02')], [Synset('weather_ship.n.01')], [Synset('galley.n.01')], [Synset('patrol_boat.n.01')], [Synset('ship.n.01')], [Synset('yacht.n.01')], [Synset('boat.n.01')]], [Synset('hovercraft.n.01')], [Synset('spacecraft.n.01'), [Synset('space_capsule.n.01')], [Synset('space_shuttle.n.01')], [Synset('lunar_excursion_module.n.01')], [Synset('starship.n.01')], [Synset('lander.n.02')]]], [Synset('bumper_car.n.01')], [Synset('steamroller.n.02')], [Synset('skibob.n.01')], [Synset('sled.n.01'), [Synset('bobsled.n.01')], [Synset('dogsled.n.01')], [Synset('pung.n.01')], [Synset('luge.n.01')], [Synset('bobsled.n.02')], [Synset('toboggan.n.01')]], [Synset('military_vehicle.n.01'), [Synset('weapons_carrier.n.01')], [Synset('tank.n.01'), [Synset('panzer.n.01')]], [Synset('warplane.n.01'), [Synset('fighter.n.02')], [Synset('reconnaissance_plane.n.01')], [Synset('bomber.n.01')]], [Synset('caisson.n.02')], [Synset('reconnaissance_vehicle.n.01')], [Synset('humvee.n.01')], [Synset('warship.n.01'), [Synset('frigate.n.02')], [Synset('cruiser.n.02')], [Synset('destroyer_escort.n.01')], [Synset('corvette.n.01')], [Synset('aircraft_carrier.n.01')], [Synset('destroyer.n.01')], [Synset('ironclad.n.01')], [Synset('man-of-war.n.01')], [Synset('frigate.n.01')], [Synset('privateer.n.02')], [Synset('guard_ship.n.01')], [Synset('sloop_of_war.n.01')], [Synset('three-decker.n.03')], [Synset('capital_ship.n.01')], [Synset('battleship.n.01')], [Synset('submersible.n.02')], [Synset('surface_ship.n.01')], [Synset('torpedo_boat.n.01')]], [Synset('picket.n.04'), [Synset('picket_ship.n.01')], [Synset('picket_boat.n.01')]], [Synset('technical.n.01')], [Synset('troop_carrier.n.01'), [Synset('troopship.n.01')]], [Synset('half_track.n.01')], [Synset('personnel_carrier.n.01')]], [Synset('wheeled_vehicle.n.01'), [Synset('unicycle.n.01')], [Synset('skateboard.n.01')], [Synset('boneshaker.n.01')], [Synset('baby_buggy.n.01'), [Synset('bassinet.n.02')]], [Synset('motor_scooter.n.01')], [Synset('welcome_wagon.n.01')], [Synset('tricycle.n.01'), [Synset('pedicab.n.01')]], [Synset('trailer.n.04'), [Synset('mobile_home.n.01')], [Synset('camper_trailer.n.01')]], [Synset('horse-drawn_vehicle.n.01'), [Synset('sulky.n.01')], [Synset('carriage.n.02')], [Synset('limber.n.01')], [Synset('chariot.n.02')]], [Synset('self-propelled_vehicle.n.01'), [Synset('weapons_carrier.n.01')], [Synset('armored_vehicle.n.01')], [Synset('carrier.n.02')], [Synset('tracked_vehicle.n.01')], [Synset('reconnaissance_vehicle.n.01')], [Synset('motor_vehicle.n.01')], [Synset('recreational_vehicle.n.01')], [Synset('forklift.n.01')], [Synset('personnel_carrier.n.01')], [Synset('tractor.n.01')], [Synset('streetcar.n.01')], [Synset('locomotive.n.01')]], [Synset('handcart.n.01'), [Synset('applecart.n.02')], [Synset('laundry_cart.n.01')], [Synset('serving_cart.n.01')], [Synset('barrow.n.03')], [Synset('shopping_cart.n.01')], [Synset('hand_truck.n.01')]], [Synset('car.n.02'), [Synset('baggage_car.n.01')], [Synset('slip_coach.n.01')], [Synset('van.n.03')], [Synset('freight_car.n.01')], [Synset('handcar.n.01')], [Synset('tender.n.04')], [Synset('mail_car.n.01')], [Synset('cabin_car.n.01')], [Synset('guard's_van.n.01')], [Synset('club_car.n.01')], [Synset('passenger_car.n.01')]], [Synset('wagon.n.04')], [Synset('scooter.n.02')], [Synset('bicycle.n.01'), [Synset('safety_bicycle.n.01')], [Synset('mountain_bike.n.01')], [Synset('velocipede.n.01')], [Synset('ordinary.n.04')], [Synset('push-bike.n.01')], [Synset('bicycle-built-for-two.n.01')]], [Synset('wagon.n.01'), [Synset('milk_wagon.n.01')], [Synset('chuck_wagon.n.01')], [Synset('cart.n.01')], [Synset('covered_wagon.n.01')], [Synset('tramcar.n.01')], [Synset('water_wagon.n.01')], [Synset('lorry.n.01')], [Synset('wain.n.03')], [Synset('bandwagon.n.02')], [Synset('ice_wagon.n.01')]], [Synset('rolling_stock.n.01')]]]

In [64]:
pprint(tree)

[Synset('vehicle.n.01'),
 [Synset('rocket.n.01'),
  [Synset('test_rocket.n.01'), [Synset('sounding_rocket.n.01')]],
  [Synset('multistage_rocket.n.01')],
  [Synset('missile.n.01'),
   [Synset('guided_missile.n.01')],
   [Synset('air-to-ground_missile.n.01')],
   [Synset('heat-seeking_missile.n.01')],
   [Synset('ballistic_missile.n.01')],
   [Synset('air-to-air_missile.n.01')],
   [Synset('sidewinder.n.02')]]],
 [Synset('craft.n.02'),
  [Synset('aircraft.n.01'),
   [Synset('stealth_aircraft.n.01')],
   [Synset('heavier-than-air_craft.n.01')],
   [Synset('cruise_missile.n.01')],
   [Synset('bogy.n.01')],
   [Synset('lighter-than-air_craft.n.01')]],
  [Synset('landing_craft.n.01')],
  [Synset('vessel.n.02'),
   [Synset('galley.n.02')],
   [Synset('sailing_vessel.n.01')],
   [Synset('shrimper.n.01')],
   [Synset('fishing_boat.n.01')],
   [Synset('bareboat.n.01')],
   [Synset('iceboat.n.02')],
   [Synset('weather_ship.n.01')],
   [Synset('galley.n.01')],
   [Synset('patrol_boat.n.01')],
   [Synset('ship.n.01')],
   [Synset('yacht.n.01')],
   [Synset('boat.n.01')]],
  [Synset('hovercraft.n.01')],
  [Synset('spacecraft.n.01'),
   [Synset('space_capsule.n.01')],
   [Synset('space_shuttle.n.01')],
   [Synset('lunar_excursion_module.n.01')],
   [Synset('starship.n.01')],
   [Synset('lander.n.02')]]],
 [Synset('bumper_car.n.01')],
 [Synset('steamroller.n.02')],
 [Synset('skibob.n.01')],
 [Synset('sled.n.01'),
  [Synset('bobsled.n.01')],
  [Synset('dogsled.n.01')],
  [Synset('pung.n.01')],
  [Synset('luge.n.01')],
  [Synset('bobsled.n.02')],
  [Synset('toboggan.n.01')]],
 [Synset('military_vehicle.n.01'),
  [Synset('weapons_carrier.n.01')],
  [Synset('tank.n.01'), [Synset('panzer.n.01')]],
  [Synset('warplane.n.01'),
   [Synset('fighter.n.02')],
   [Synset('reconnaissance_plane.n.01')],
   [Synset('bomber.n.01')]],
  [Synset('caisson.n.02')],
  [Synset('reconnaissance_vehicle.n.01')],
  [Synset('humvee.n.01')],
  [Synset('warship.n.01'),
   [Synset('frigate.n.02')],
   [Synset('cruiser.n.02')],
   [Synset('destroyer_escort.n.01')],
   [Synset('corvette.n.01')],
   [Synset('aircraft_carrier.n.01')],
   [Synset('destroyer.n.01')],
   [Synset('ironclad.n.01')],
   [Synset('man-of-war.n.01')],
   [Synset('frigate.n.01')],
   [Synset('privateer.n.02')],
   [Synset('guard_ship.n.01')],
   [Synset('sloop_of_war.n.01')],
   [Synset('three-decker.n.03')],
   [Synset('capital_ship.n.01')],
   [Synset('battleship.n.01')],
   [Synset('submersible.n.02')],
   [Synset('surface_ship.n.01')],
   [Synset('torpedo_boat.n.01')]],
  [Synset('picket.n.04'),
   [Synset('picket_ship.n.01')],
   [Synset('picket_boat.n.01')]],
  [Synset('technical.n.01')],
  [Synset('troop_carrier.n.01'), [Synset('troopship.n.01')]],
  [Synset('half_track.n.01')],
  [Synset('personnel_carrier.n.01')]],
 [Synset('wheeled_vehicle.n.01'),
  [Synset('unicycle.n.01')],
  [Synset('skateboard.n.01')],
  [Synset('boneshaker.n.01')],
  [Synset('baby_buggy.n.01'), [Synset('bassinet.n.02')]],
  [Synset('motor_scooter.n.01')],
  [Synset('welcome_wagon.n.01')],
  [Synset('tricycle.n.01'), [Synset('pedicab.n.01')]],
  [Synset('trailer.n.04'),
   [Synset('mobile_home.n.01')],
   [Synset('camper_trailer.n.01')]],
  [Synset('horse-drawn_vehicle.n.01'),
   [Synset('sulky.n.01')],
   [Synset('carriage.n.02')],
   [Synset('limber.n.01')],
   [Synset('chariot.n.02')]],
  [Synset('self-propelled_vehicle.n.01'),
   [Synset('weapons_carrier.n.01')],
   [Synset('armored_vehicle.n.01')],
   [Synset('carrier.n.02')],
   [Synset('tracked_vehicle.n.01')],
   [Synset('reconnaissance_vehicle.n.01')],
   [Synset('motor_vehicle.n.01')],
   [Synset('recreational_vehicle.n.01')],
   [Synset('forklift.n.01')],
   [Synset('personnel_carrier.n.01')],
   [Synset('tractor.n.01')],
   [Synset('streetcar.n.01')],
   [Synset('locomotive.n.01')]],
  [Synset('handcart.n.01'),
   [Synset('applecart.n.02')],
   [Synset('laundry_cart.n.01')],
   [Synset('serving_cart.n.01')],
   [Synset('barrow.n.03')],
   [Synset('shopping_cart.n.01')],
   [Synset('hand_truck.n.01')]],
  [Synset('car.n.02'),
   [Synset('baggage_car.n.01')],
   [Synset('slip_coach.n.01')],
   [Synset('van.n.03')],
   [Synset('freight_car.n.01')],
   [Synset('handcar.n.01')],
   [Synset('tender.n.04')],
   [Synset('mail_car.n.01')],
   [Synset('cabin_car.n.01')],
   [Synset('guard's_van.n.01')],
   [Synset('club_car.n.01')],
   [Synset('passenger_car.n.01')]],
  [Synset('wagon.n.04')],
  [Synset('scooter.n.02')],
  [Synset('bicycle.n.01'),
   [Synset('safety_bicycle.n.01')],
   [Synset('mountain_bike.n.01')],
   [Synset('velocipede.n.01')],
   [Synset('ordinary.n.04')],
   [Synset('push-bike.n.01')],
   [Synset('bicycle-built-for-two.n.01')]],
  [Synset('wagon.n.01'),
   [Synset('milk_wagon.n.01')],
   [Synset('chuck_wagon.n.01')],
   [Synset('cart.n.01')],
   [Synset('covered_wagon.n.01')],
   [Synset('tramcar.n.01')],
   [Synset('water_wagon.n.01')],
   [Synset('lorry.n.01')],
   [Synset('wain.n.03')],
   [Synset('bandwagon.n.02')],
   [Synset('ice_wagon.n.01')]],
  [Synset('rolling_stock.n.01')]]]

In [65]:
def get_nodes(tree):
    #in input si manda la struttura tree di synset 
    #restituisce una lista di nodi con ilemmi corrispondenti ai synset ottenuti
    nodes = []
    node = tree[0]
    nodes.append(node)

    for child in tree[1:]:
        nodes.extend(get_nodes(child))

    return nodes
nodes = get_nodes(tree)

print(nodes)

[Synset('vehicle.n.01'), Synset('rocket.n.01'), Synset('test_rocket.n.01'), Synset('sounding_rocket.n.01'), Synset('multistage_rocket.n.01'), Synset('missile.n.01'), Synset('guided_missile.n.01'), Synset('air-to-ground_missile.n.01'), Synset('heat-seeking_missile.n.01'), Synset('ballistic_missile.n.01'), Synset('air-to-air_missile.n.01'), Synset('sidewinder.n.02'), Synset('craft.n.02'), Synset('aircraft.n.01'), Synset('stealth_aircraft.n.01'), Synset('heavier-than-air_craft.n.01'), Synset('cruise_missile.n.01'), Synset('bogy.n.01'), Synset('lighter-than-air_craft.n.01'), Synset('landing_craft.n.01'), Synset('vessel.n.02'), Synset('galley.n.02'), Synset('sailing_vessel.n.01'), Synset('shrimper.n.01'), Synset('fishing_boat.n.01'), Synset('bareboat.n.01'), Synset('iceboat.n.02'), Synset('weather_ship.n.01'), Synset('galley.n.01'), Synset('patrol_boat.n.01'), Synset('ship.n.01'), Synset('yacht.n.01'), Synset('boat.n.01'), Synset('hovercraft.n.01'), Synset('spacecraft.n.01'), Synset('space_capsule.n.01'), Synset('space_shuttle.n.01'), Synset('lunar_excursion_module.n.01'), Synset('starship.n.01'), Synset('lander.n.02'), Synset('bumper_car.n.01'), Synset('steamroller.n.02'), Synset('skibob.n.01'), Synset('sled.n.01'), Synset('bobsled.n.01'), Synset('dogsled.n.01'), Synset('pung.n.01'), Synset('luge.n.01'), Synset('bobsled.n.02'), Synset('toboggan.n.01'), Synset('military_vehicle.n.01'), Synset('weapons_carrier.n.01'), Synset('tank.n.01'), Synset('panzer.n.01'), Synset('warplane.n.01'), Synset('fighter.n.02'), Synset('reconnaissance_plane.n.01'), Synset('bomber.n.01'), Synset('caisson.n.02'), Synset('reconnaissance_vehicle.n.01'), Synset('humvee.n.01'), Synset('warship.n.01'), Synset('frigate.n.02'), Synset('cruiser.n.02'), Synset('destroyer_escort.n.01'), Synset('corvette.n.01'), Synset('aircraft_carrier.n.01'), Synset('destroyer.n.01'), Synset('ironclad.n.01'), Synset('man-of-war.n.01'), Synset('frigate.n.01'), Synset('privateer.n.02'), Synset('guard_ship.n.01'), Synset('sloop_of_war.n.01'), Synset('three-decker.n.03'), Synset('capital_ship.n.01'), Synset('battleship.n.01'), Synset('submersible.n.02'), Synset('surface_ship.n.01'), Synset('torpedo_boat.n.01'), Synset('picket.n.04'), Synset('picket_ship.n.01'), Synset('picket_boat.n.01'), Synset('technical.n.01'), Synset('troop_carrier.n.01'), Synset('troopship.n.01'), Synset('half_track.n.01'), Synset('personnel_carrier.n.01'), Synset('wheeled_vehicle.n.01'), Synset('unicycle.n.01'), Synset('skateboard.n.01'), Synset('boneshaker.n.01'), Synset('baby_buggy.n.01'), Synset('bassinet.n.02'), Synset('motor_scooter.n.01'), Synset('welcome_wagon.n.01'), Synset('tricycle.n.01'), Synset('pedicab.n.01'), Synset('trailer.n.04'), Synset('mobile_home.n.01'), Synset('camper_trailer.n.01'), Synset('horse-drawn_vehicle.n.01'), Synset('sulky.n.01'), Synset('carriage.n.02'), Synset('limber.n.01'), Synset('chariot.n.02'), Synset('self-propelled_vehicle.n.01'), Synset('weapons_carrier.n.01'), Synset('armored_vehicle.n.01'), Synset('carrier.n.02'), Synset('tracked_vehicle.n.01'), Synset('reconnaissance_vehicle.n.01'), Synset('motor_vehicle.n.01'), Synset('recreational_vehicle.n.01'), Synset('forklift.n.01'), Synset('personnel_carrier.n.01'), Synset('tractor.n.01'), Synset('streetcar.n.01'), Synset('locomotive.n.01'), Synset('handcart.n.01'), Synset('applecart.n.02'), Synset('laundry_cart.n.01'), Synset('serving_cart.n.01'), Synset('barrow.n.03'), Synset('shopping_cart.n.01'), Synset('hand_truck.n.01'), Synset('car.n.02'), Synset('baggage_car.n.01'), Synset('slip_coach.n.01'), Synset('van.n.03'), Synset('freight_car.n.01'), Synset('handcar.n.01'), Synset('tender.n.04'), Synset('mail_car.n.01'), Synset('cabin_car.n.01'), Synset('guard's_van.n.01'), Synset('club_car.n.01'), Synset('passenger_car.n.01'), Synset('wagon.n.04'), Synset('scooter.n.02'), Synset('bicycle.n.01'), Synset('safety_bicycle.n.01'), Synset('mountain_bike.n.01'), Synset('velocipede.n.01'), Synset('ordinary.n.04'), Synset('push-bike.n.01'), Synset('bicycle-built-for-two.n.01'), Synset('wagon.n.01'), Synset('milk_wagon.n.01'), Synset('chuck_wagon.n.01'), Synset('cart.n.01'), Synset('covered_wagon.n.01'), Synset('tramcar.n.01'), Synset('water_wagon.n.01'), Synset('lorry.n.01'), Synset('wain.n.03'), Synset('bandwagon.n.02'), Synset('ice_wagon.n.01'), Synset('rolling_stock.n.01')]

In [66]:
print(vehicle.shortest_path_distance(wn.synset("craft.n.02")))
print(vehicle.shortest_path_distance(wn.synset("vessel.n.02")))
print(vehicle.shortest_path_distance(wn.synset("ship.n.01")))

1
2
3

In [67]:
for synset in nodes[:10]:
    print(synset.name(), "->", synset.lemmas()[0].name())

vehicle.n.01 -> vehicle
rocket.n.01 -> rocket
test_rocket.n.01 -> test_rocket
sounding_rocket.n.01 -> sounding_rocket
multistage_rocket.n.01 -> multistage_rocket
missile.n.01 -> missile
guided_missile.n.01 -> guided_missile
air-to-ground_missile.n.01 -> air-to-ground_missile
heat-seeking_missile.n.01 -> heat-seeking_missile
ballistic_missile.n.01 -> ballistic_missile

In [68]:
#si crea lista di lemmi: ogni lemma in lista è nella stessa posizione del corrispettivo synset in nodes
words = [synset.lemmas()[0].name() for synset in nodes]

print(words)

['vehicle', 'rocket', 'test_rocket', 'sounding_rocket', 'multistage_rocket', 'missile', 'guided_missile', 'air-to-ground_missile', 'heat-seeking_missile', 'ballistic_missile', 'air-to-air_missile', 'sidewinder', 'craft', 'aircraft', 'stealth_aircraft', 'heavier-than-air_craft', 'cruise_missile', 'bogy', 'lighter-than-air_craft', 'landing_craft', 'vessel', 'galley', 'sailing_vessel', 'shrimper', 'fishing_boat', 'bareboat', 'iceboat', 'weather_ship', 'galley', 'patrol_boat', 'ship', 'yacht', 'boat', 'hovercraft', 'spacecraft', 'space_capsule', 'space_shuttle', 'lunar_excursion_module', 'starship', 'lander', 'bumper_car', 'steamroller', 'skibob', 'sled', 'bobsled', 'dogsled', 'pung', 'luge', 'bobsled', 'toboggan', 'military_vehicle', 'weapons_carrier', 'tank', 'panzer', 'warplane', 'fighter', 'reconnaissance_plane', 'bomber', 'caisson', 'reconnaissance_vehicle', 'Humvee', 'warship', 'frigate', 'cruiser', 'destroyer_escort', 'corvette', 'aircraft_carrier', 'destroyer', 'ironclad', 'man-of-war', 'frigate', 'privateer', 'guard_ship', 'sloop_of_war', 'three-decker', 'capital_ship', 'battleship', 'submersible', 'surface_ship', 'torpedo_boat', 'picket', 'picket_ship', 'picket_boat', 'technical', 'troop_carrier', 'troopship', 'half_track', 'personnel_carrier', 'wheeled_vehicle', 'unicycle', 'skateboard', 'boneshaker', 'baby_buggy', 'bassinet', 'motor_scooter', 'welcome_wagon', 'tricycle', 'pedicab', 'trailer', 'mobile_home', 'camper_trailer', 'horse-drawn_vehicle', 'sulky', 'carriage', 'limber', 'chariot', 'self-propelled_vehicle', 'weapons_carrier', 'armored_vehicle', 'carrier', 'tracked_vehicle', 'reconnaissance_vehicle', 'motor_vehicle', 'recreational_vehicle', 'forklift', 'personnel_carrier', 'tractor', 'streetcar', 'locomotive', 'handcart', 'applecart', 'laundry_cart', 'serving_cart', 'barrow', 'shopping_cart', 'hand_truck', 'car', 'baggage_car', 'slip_coach', 'van', 'freight_car', 'handcar', 'tender', 'mail_car', 'cabin_car', "guard's_van", 'club_car', 'passenger_car', 'wagon', 'scooter', 'bicycle', 'safety_bicycle', 'mountain_bike', 'velocipede', 'ordinary', 'push-bike', 'bicycle-built-for-two', 'wagon', 'milk_wagon', 'chuck_wagon', 'cart', 'covered_wagon', 'tramcar', 'water_wagon', 'lorry', 'wain', 'bandwagon', 'ice_wagon', 'rolling_stock']

In [69]:
filtered_nodes_unique = []
seen_lemmas = set()

for node in filtered_nodes:
    lemma = node.lemmas()[0].name()

    if lemma not in seen_lemmas:
        filtered_nodes_unique.append(node)
        seen_lemmas.add(lemma)

In [70]:
print("Nodi originali:", len(nodes))
print("Nodi filtrati:", len(filtered_nodes))

Nodi originali: 159
Nodi filtrati: 68

In [71]:
for synset in filtered_nodes:
    print(synset.name(), "->", synset.lemmas()[0].name())
    
#si crea lista di lemmi: ogni lemma in lista è nella stessa posizione del corrispettivo synset in nodes
lemmas = [synset.lemmas()[0].name() for synset in filtered_nodes]

print(lemmas)

vehicle.n.01 -> vehicle
rocket.n.01 -> rocket
missile.n.01 -> missile
sidewinder.n.02 -> sidewinder
craft.n.02 -> craft
aircraft.n.01 -> aircraft
vessel.n.02 -> vessel
galley.n.02 -> galley
galley.n.01 -> galley
ship.n.01 -> ship
yacht.n.01 -> yacht
boat.n.01 -> boat
hovercraft.n.01 -> hovercraft
spacecraft.n.01 -> spacecraft
starship.n.01 -> starship
lander.n.02 -> lander
steamroller.n.02 -> steamroller
sled.n.01 -> sled
bobsled.n.01 -> bobsled
luge.n.01 -> luge
bobsled.n.02 -> bobsled
toboggan.n.01 -> toboggan
tank.n.01 -> tank
panzer.n.01 -> panzer
warplane.n.01 -> warplane
fighter.n.02 -> fighter
bomber.n.01 -> bomber
caisson.n.02 -> caisson
humvee.n.01 -> Humvee
warship.n.01 -> warship
frigate.n.02 -> frigate
cruiser.n.02 -> cruiser
corvette.n.01 -> corvette
destroyer.n.01 -> destroyer
ironclad.n.01 -> ironclad
frigate.n.01 -> frigate
privateer.n.02 -> privateer
battleship.n.01 -> battleship
submersible.n.02 -> submersible
picket.n.04 -> picket
technical.n.01 -> technical
unicycle.n.01 -> unicycle
skateboard.n.01 -> skateboard
bassinet.n.02 -> bassinet
tricycle.n.01 -> tricycle
trailer.n.04 -> trailer
sulky.n.01 -> sulky
carriage.n.02 -> carriage
limber.n.01 -> limber
chariot.n.02 -> chariot
carrier.n.02 -> carrier
forklift.n.01 -> forklift
tractor.n.01 -> tractor
streetcar.n.01 -> streetcar
locomotive.n.01 -> locomotive
barrow.n.03 -> barrow
car.n.02 -> car
van.n.03 -> van
tender.n.04 -> tender
wagon.n.04 -> wagon
scooter.n.02 -> scooter
bicycle.n.01 -> bicycle
ordinary.n.04 -> ordinary
wagon.n.01 -> wagon
cart.n.01 -> cart
lorry.n.01 -> lorry
wain.n.03 -> wain
bandwagon.n.02 -> bandwagon
['vehicle', 'rocket', 'missile', 'sidewinder', 'craft', 'aircraft', 'vessel', 'galley', 'galley', 'ship', 'yacht', 'boat', 'hovercraft', 'spacecraft', 'starship', 'lander', 'steamroller', 'sled', 'bobsled', 'luge', 'bobsled', 'toboggan', 'tank', 'panzer', 'warplane', 'fighter', 'bomber', 'caisson', 'Humvee', 'warship', 'frigate', 'cruiser', 'corvette', 'destroyer', 'ironclad', 'frigate', 'privateer', 'battleship', 'submersible', 'picket', 'technical', 'unicycle', 'skateboard', 'bassinet', 'tricycle', 'trailer', 'sulky', 'carriage', 'limber', 'chariot', 'carrier', 'forklift', 'tractor', 'streetcar', 'locomotive', 'barrow', 'car', 'van', 'tender', 'wagon', 'scooter', 'bicycle', 'ordinary', 'wagon', 'cart', 'lorry', 'wain', 'bandwagon']

In [72]:
#Altro filtro da applicare: polisemia: se compare una parola associata a due synset diversi nell'albero.
#prima controlliamo nell'insieme dei nodi non filtrati
counts = Counter(lemmas) 
duplicates = {word: count for word, count in counts.items() if count > 1} 
print(duplicates)

{'galley': 2, 'bobsled': 2, 'frigate': 2, 'wagon': 2}

In [73]:
#adesso controlliamo nei nodi filtreti, si sono già ridotte
for synset in filtered_nodes:
    word = synset.lemmas()[0].name()

    if word in duplicates:
        print(synset.name(), "->", word)

galley.n.02 -> galley
galley.n.01 -> galley
bobsled.n.01 -> bobsled
bobsled.n.02 -> bobsled
frigate.n.02 -> frigate
frigate.n.01 -> frigate
wagon.n.04 -> wagon
wagon.n.01 -> wagon

In [74]:
#  contiamo quanti lemmi uguali ci sono che appartengono a synset diversi --> li filitriamo mantenendo i lemmi contati una sola volta
counts = Counter(
    synset.lemmas()[0].name()
    for synset in filtered_nodes
)

filtered_nodes_unique = [
    synset
    for synset in filtered_nodes
    if counts[synset.lemmas()[0].name()] == 1
]

print("Nodi prima:", len(filtered_nodes))
print("Nodi dopo:", len(filtered_nodes_unique))

Nodi prima: 68
Nodi dopo: 60

In [75]:
#creiamo lista di liste contenenti lemma 1, lemma 2, e la distanza tassonomica dei corrispettivi synset
pairs = []

for i in range(len(filtered_nodes_unique)):
    for j in range(i + 1, len(filtered_nodes_unique)):

        synset1 = filtered_nodes_unique[i]
        synset2 = filtered_nodes_unique[j]

        distance = synset1.shortest_path_distance(synset2)

        if distance is not None:
            word1 = synset1.lemmas()[0].name()
            word2 = synset2.lemmas()[0].name()

            pairs.append((word1, word2, distance))

In [76]:
synset1 = nodes[0]
synset2 = nodes[1]

word1 = words[0]
word2 = words[1]

distance = synset1.shortest_path_distance(synset2)

print(word1, "-", word2, "->", distance)

vehicle - rocket -> 1

In [77]:
#creiamo lista di liste contenenti memma 1, lemma 2, e la distanza tassonomica dei corrispettivi synset 
pairs = []

for i in range(len(nodes)):
    for j in range(i + 1, len(nodes)):
        
        synset1 = nodes[i]
        synset2 = nodes[j]
        
        word1 = words[i]
        word2 = words[j]
        
        distance = synset1.shortest_path_distance(synset2)
        
        pairs.append([word1, word2, distance])

In [78]:
df = pd.DataFrame(
    pairs,
    columns=["word1", "word2", "taxonomic_distance"]
)

df

           word1              word2  taxonomic_distance
0        vehicle             rocket                   1
1        vehicle        test_rocket                   2
2        vehicle    sounding_rocket                   3
3        vehicle  multistage_rocket                   2
4        vehicle            missile                   2
...          ...                ...                 ...
12556       wain          ice_wagon                   2
12557       wain      rolling_stock                   3
12558  bandwagon          ice_wagon                   2
12559  bandwagon      rolling_stock                   3
12560  ice_wagon      rolling_stock                   3

[12561 rows x 3 columns]

In [79]:
df.head(20)

      word1                   word2  taxonomic_distance
0   vehicle                  rocket                   1
1   vehicle             test_rocket                   2
2   vehicle         sounding_rocket                   3
3   vehicle       multistage_rocket                   2
4   vehicle                 missile                   2
5   vehicle          guided_missile                   3
6   vehicle   air-to-ground_missile                   3
7   vehicle    heat-seeking_missile                   3
8   vehicle       ballistic_missile                   3
9   vehicle      air-to-air_missile                   3
10  vehicle              sidewinder                   3
11  vehicle                   craft                   1
12  vehicle                aircraft                   2
13  vehicle        stealth_aircraft                   3
14  vehicle  heavier-than-air_craft                   3
15  vehicle          cruise_missile                   3
16  vehicle                    bogy                   3
17  vehicle  lighter-than-air_craft                   3
18  vehicle           landing_craft                   2
19  vehicle                  vessel                   2

In [80]:
df["taxonomic_distance"].value_counts().sort_index()

taxonomic_distance
0       3
1     170
2     964
3    1850
4    3182
5    3075
6    3317
Name: count, dtype: int64

In [81]:
#eliminare ripetizioni di parole
df = df[df["taxonomic_distance"] > 0]

In [82]:
df["taxonomic_distance"].value_counts().sort_index()

taxonomic_distance
1     170
2     964
3    1850
4    3182
5    3075
6    3317
Name: count, dtype: int64

In [83]:
#vogliamo creare un albero più piccolo per la nostra analisi
#calcoliamo quanti iponomi producono gli iponomi di vehicles
branches = vehicle.hyponyms()

for branch in branches:
    print(branch.name(), "->", len(branch.hyponyms()), "figli")

rocket.n.01 -> 3 figli
craft.n.02 -> 5 figli
bumper_car.n.01 -> 0 figli
steamroller.n.02 -> 0 figli
skibob.n.01 -> 0 figli
sled.n.01 -> 6 figli
military_vehicle.n.01 -> 12 figli
wheeled_vehicle.n.01 -> 17 figli

In [84]:
for node in filtered_nodes_unique:
    print(node.name(), node.lemma_names())

vehicle.n.01 ['vehicle']
rocket.n.01 ['rocket', 'projectile']
missile.n.01 ['missile']
sidewinder.n.02 ['sidewinder']
craft.n.02 ['craft']
aircraft.n.01 ['aircraft']
vessel.n.02 ['vessel', 'watercraft']
ship.n.01 ['ship']
yacht.n.01 ['yacht', 'racing_yacht']
boat.n.01 ['boat']
hovercraft.n.01 ['hovercraft', 'ground-effect_machine']
spacecraft.n.01 ['spacecraft', 'ballistic_capsule', 'space_vehicle']
starship.n.01 ['starship', 'spaceship']
lander.n.02 ['lander']
steamroller.n.02 ['steamroller', 'road_roller']
sled.n.01 ['sled', 'sledge', 'sleigh']
luge.n.01 ['luge']
toboggan.n.01 ['toboggan']
tank.n.01 ['tank', 'army_tank', 'armored_combat_vehicle', 'armoured_combat_vehicle']
panzer.n.01 ['panzer']
warplane.n.01 ['warplane', 'military_plane']
fighter.n.02 ['fighter', 'fighter_aircraft', 'attack_aircraft']
bomber.n.01 ['bomber']
caisson.n.02 ['caisson']
humvee.n.01 ['Humvee', 'Hum-Vee']
warship.n.01 ['warship', 'war_vessel', 'combat_ship']
cruiser.n.02 ['cruiser']
corvette.n.01 ['corvette']
destroyer.n.01 ['destroyer', 'guided_missile_destroyer']
ironclad.n.01 ['ironclad']
privateer.n.02 ['privateer']
battleship.n.01 ['battleship', 'battlewagon']
submersible.n.02 ['submersible', 'submersible_warship']
picket.n.04 ['picket']
technical.n.01 ['technical']
unicycle.n.01 ['unicycle', 'monocycle']
skateboard.n.01 ['skateboard']
bassinet.n.02 ['bassinet']
tricycle.n.01 ['tricycle', 'trike', 'velocipede']
trailer.n.04 ['trailer', 'house_trailer']
sulky.n.01 ['sulky']
carriage.n.02 ['carriage', 'equipage', 'rig']
limber.n.01 ['limber']
chariot.n.02 ['chariot']
carrier.n.02 ['carrier']
forklift.n.01 ['forklift']
tractor.n.01 ['tractor']
streetcar.n.01 ['streetcar', 'tram', 'tramcar', 'trolley', 'trolley_car']
locomotive.n.01 ['locomotive', 'engine', 'locomotive_engine', 'railway_locomotive']
barrow.n.03 ['barrow', 'garden_cart', 'lawn_cart', 'wheelbarrow']
car.n.02 ['car', 'railcar', 'railway_car', 'railroad_car']
van.n.03 ['van']
tender.n.04 ['tender']
scooter.n.02 ['scooter']
bicycle.n.01 ['bicycle', 'bike', 'wheel', 'cycle']
ordinary.n.04 ['ordinary', 'ordinary_bicycle']
cart.n.01 ['cart']
lorry.n.01 ['lorry']
wain.n.03 ['wain']
bandwagon.n.02 ['bandwagon']

In [85]:
#controlliamo quanti iponomi producono gli iponomi di vehicles ma il tutto per la nostra lista filtrata
#in pratica creiamo una lista contenente per ogni branca, la radice stessa più tutti gli iponomi conservati dopo i filtri
for branch in vehicle.hyponyms():
    nodes_in_branch = [
        node for node in filtered_nodes_unique
        if node == branch
        or any(branch in path for path in node.hypernym_paths())
    ]

    print(branch.name(), "->", len(nodes_in_branch), "nodi")

rocket.n.01 -> 3 nodi
craft.n.02 -> 21 nodi
bumper_car.n.01 -> 0 nodi
steamroller.n.02 -> 1 nodi
skibob.n.01 -> 0 nodi
sled.n.01 -> 3 nodi
military_vehicle.n.01 -> 17 nodi
wheeled_vehicle.n.01 -> 28 nodi

In [86]:
#leggere da qua
root = vehicle

In [87]:
def get_nodes_depth(root, max_depth=3):
    nodes = {root}
    current_level = [root]

    for _ in range(max_depth):
        next_level = []

        for node in current_level:
            children = node.hyponyms()
            next_level.extend(children)

        nodes.update(next_level)
        current_level = next_level

    return list(nodes)

In [88]:
def valid_node(synset):
    lemma = synset.lemmas()[0].name()

    return (
        lemma.isalpha()
        and len(lemma) >= 3
        and zipf_frequency(lemma, "en") >= 2
    )

In [89]:
filtered_nodes = [
    synset for synset in nodes
    if valid_node(synset)
]

In [90]:
nodes = [vehicle]

for synset in vehicle.hyponyms():
    nodes.append(synset)

    for child in synset.hyponyms():
        nodes.append(child)

        for grandchild in child.hyponyms():
            nodes.append(grandchild)

In [91]:
filtered_nodes = [
    node for node in nodes
    if valid_node(node)
]

In [92]:

filtered_nodes_unique = []
seen_lemmas = set()

for node in filtered_nodes:
    lemma = node.lemmas()[0].name()

    if lemma not in seen_lemmas:
        filtered_nodes_unique.append(node)
        seen_lemmas.add(lemma)

In [93]:
print("Nodi totali:", len(nodes))
print("Nodi dopo il filtro:", len(filtered_nodes))
print("Nodi unici:", len(filtered_nodes_unique))

Nodi totali: 159
Nodi dopo il filtro: 68
Nodi unici: 64

In [94]:
filtered_set = set(filtered_nodes_unique)

print("vehicle")

for synset in vehicle.hyponyms():

    if synset in filtered_set:
        print("├──", synset.lemmas()[0].name())

        for child in synset.hyponyms():

            if child in filtered_set:
                print("│   ├──", child.lemmas()[0].name())

                for grandchild in child.hyponyms():

                    if grandchild in filtered_set:
                        print("│   │   └──", grandchild.lemmas()[0].name())

vehicle
├── rocket
│   ├── missile
│   │   └── sidewinder
├── craft
│   ├── aircraft
│   ├── vessel
│   │   └── galley
│   │   └── ship
│   │   └── yacht
│   │   └── boat
│   ├── hovercraft
│   ├── spacecraft
│   │   └── starship
│   │   └── lander
├── steamroller
├── sled
│   ├── bobsled
│   ├── luge
│   ├── toboggan

In [95]:
final_words = [
    "vehicle",
    "rocket",
    "missile",
    "sidewinder",
    "craft",
    "aircraft",
    "vessel",
    "galley",
    "ship",
    "yacht",
    "boat",
    "hovercraft",
    "spacecraft",
    "starship",
    "lander",
    "steamroller",
    "sled",
    "bobsled",
    "luge",
    "toboggan"
]

In [96]:
final_nodes = [
    node
    for node in filtered_nodes_unique
    if node.lemmas()[0].name() in final_words
]

print("Nodi finali:", len(final_nodes))

Nodi finali: 20

In [97]:
for node in final_nodes:
    print(node.name(), "->", node.lemmas()[0].name())

vehicle.n.01 -> vehicle
rocket.n.01 -> rocket
missile.n.01 -> missile
sidewinder.n.02 -> sidewinder
craft.n.02 -> craft
aircraft.n.01 -> aircraft
vessel.n.02 -> vessel
galley.n.02 -> galley
ship.n.01 -> ship
yacht.n.01 -> yacht
boat.n.01 -> boat
hovercraft.n.01 -> hovercraft
spacecraft.n.01 -> spacecraft
starship.n.01 -> starship
lander.n.02 -> lander
steamroller.n.02 -> steamroller
sled.n.01 -> sled
bobsled.n.01 -> bobsled
luge.n.01 -> luge
toboggan.n.01 -> toboggan

In [98]:
final_nodes = [
    node
    for node in filtered_nodes_unique
    if node.lemmas()[0].name() in final_words
]

print("Nodi finali:", len(final_nodes))

for node in final_nodes:
    print(node.name(), "->", node.lemmas()[0].name())

Nodi finali: 20
vehicle.n.01 -> vehicle
rocket.n.01 -> rocket
missile.n.01 -> missile
sidewinder.n.02 -> sidewinder
craft.n.02 -> craft
aircraft.n.01 -> aircraft
vessel.n.02 -> vessel
galley.n.02 -> galley
ship.n.01 -> ship
yacht.n.01 -> yacht
boat.n.01 -> boat
hovercraft.n.01 -> hovercraft
spacecraft.n.01 -> spacecraft
starship.n.01 -> starship
lander.n.02 -> lander
steamroller.n.02 -> steamroller
sled.n.01 -> sled
bobsled.n.01 -> bobsled
luge.n.01 -> luge
toboggan.n.01 -> toboggan

In [50]:
#Altro filtro da applicare: polisemia: se compare una parola associata a due synset diversi nell'albero.
#prima controlliamo nell'insieme dei nodi non filtrati
lemmas = [node.lemmas()[0].name() for node in filtered_nodes_unique]
counts = Counter(lemmas)
duplicates = {word: count
              for word, count in counts.items() 
              if count > 1} 
print(duplicates)

{'wagon': 2, 'galley': 2, 'frigate': 2, 'bobsled': 2}

In [99]:
words = [node.lemmas()[0].name() for node in final_nodes]

pairs = []

for i in range(len(final_nodes)):
    for j in range(i + 1, len(final_nodes)):

        synset1 = final_nodes[i]
        synset2 = final_nodes[j]

        word1 = words[i]
        word2 = words[j]

        distance = synset1.shortest_path_distance(synset2)

        pairs.append([word1, word2, distance])

print("Nodi:", len(final_nodes))
print("Coppie:", len(pairs))

Nodi: 20
Coppie: 190

In [101]:
import pandas as pd

df_pairs = pd.DataFrame(
    pairs,
    columns=["word1", "word2", "taxonomic_distance"]
)

print(df_pairs.head())
print("Numero di coppie:", len(df_pairs))

     word1       word2  taxonomic_distance
0  vehicle      rocket                   1
1  vehicle     missile                   2
2  vehicle  sidewinder                   3
3  vehicle       craft                   1
4  vehicle    aircraft                   2
Numero di coppie: 190

In [103]:
df_pairs["taxonomic_distance"].value_counts().sort_index()

taxonomic_distance
1    19
2    37
3    49
4    48
5    31
6     6
Name: count, dtype: int64

In [104]:
df_pairs.to_csv("taxonomic_pairs.csv", index=False)